### ISSUE TITLE
Problemas de asincronismo con actions

### ISSUE THREAD

**Issue by juanmardefago** [PracticaDS/pdes-tp-buggysoft#42]
Dado que la actions son asincronicas, pueden ocurrir 2 actions iguales al mismo tiempo, y teniendo en cuenta que van modificando el estado, y en muchos casos recursos compartidos, se producen algunos problemas anteriormente inesperados.

Intentado implementar el transporter, que deberia ser sencillo, note que agregando 3 transporters rapidamente uno abajo del otro, si bien se mostraban bien en la grilla, internamente, los 3 tenian la misma posicion (5,2) a pesar de que deberian tener 3,2 - 4,2 - 5,2.

Deberiamos hacer un refactor de las actions para corregir esto.

**Comment by glmaljkovich** [comment]
Mala mía, es un problema de pasaje por referencia en realidad :grin: 
Despues pusheo un fix, es una boludez. Esta pegando la referencia de la currentMachine y le pisa la posicion, pero todos comparten la misma instancia.
